"""Generate README markup and styled text SVGs from profile.json."""

import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / 'assets'
profile = json.loads((ROOT / 'profile.json').read_text())
heading = escape(profile['heading'])
subtitle = escape(profile['subtitle'])
languages = escape(' · '.join(profile['languages']))
tools = escape(' · '.join(profile['tools']))
footer = escape(profile['footer'])
font = "ui-monospace, 'JetBrains Mono', 'Fira Code', SFMono-Regular, Menlo, Consolas, monospace"

for theme, primary, secondary in (
    ('light', '#182147', '#74709e'),
    ('dark', '#e2e7ff', '#aaa7cc'),
):
    header = f'''<svg xmlns="http://www.w3.org/2000/svg" width="750" height="270" viewBox="0 0 750 270" role="img" aria-labelledby="title desc">
  <title id="title">{heading}</title>
  <desc id="desc">{subtitle}. {languages}. {tools}.</desc>
  <g text-anchor="middle" font-family="{font}">
    <text x="347" y="101" fill="{primary}" font-size="50" font-weight="700">{heading}</text>
    <path d="M585 65C563 63 552 83 562 98C570 111 589 111 599 97C580 104 571 82 585 65Z" fill="#d98289"/>
    <text x="375" y="142" fill="{secondary}" font-size="21">{subtitle}</text>
    <g fill="{primary}" font-size="21">
      <text x="375" y="205">{languages}</text>
      <text x="375" y="240">{tools}</text>
    </g>
  </g>
</svg>
'''
    footer_svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="750" height="70" viewBox="0 0 750 70" role="img" aria-labelledby="title">
  <title id="title">{footer}</title>
  <text x="375" y="42" text-anchor="middle" font-family="{font}" fill="{secondary}" font-size="17">{footer}</text>
</svg>
'''
    (ASSETS / f'profile-{theme}.svg').write_text(header)
    (ASSETS / f'profile-footer-{theme}.svg').write_text(footer_svg)


def picture(name, alt):
    return f'''<picture>
    <source media="(prefers-color-scheme: dark)" srcset="assets/{name}-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="assets/{name}-light.svg">
    <img src="assets/{name}-light.svg" alt="{alt}" width="68%">
  </picture>'''


links = '&nbsp;&nbsp;&nbsp;&nbsp;'.join(
    f'<a href="{escape(link["url"], quote=True)}">{escape(link["label"])}</a>'
    for link in profile['links']
)
readme = f'''<!-- Generated by scripts/generate-profile.py. Edit profile.json for profile text and links. -->
<div id="profile-card" align="center">
  <img align="right" src="assets/moon-knight-ribbon.gif" alt="{escape(profile['knight_alt'])}" width="25%">
  {picture('profile', f'{heading} — {subtitle}. {languages}. {tools}.')}
  <br>
  <img src="assets/stars-left.svg" alt="" width="4%">
  &nbsp;
  <img src="assets/sword-divider.gif" alt="{escape(profile['sword_alt'])}" width="22%">
  &nbsp;
  <img src="assets/stars-right.svg" alt="" width="4%">
  <br>
  {picture('profile-footer', footer)}
  <br>
  <samp>{links}</samp>
  <br clear="all">
</div>
'''
(ROOT / 'README.md').write_text(readme)
